
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class tablero extends javax.swing.JFrame {

    /**
     * Creates new form tablero  
     */
    public tablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pantalla1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        pantalla2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("dado");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pantalla1.setColumns(20);
        pantalla1.setRows(5);
        pantalla1.setText("X");
        jScrollPane1.setViewportView(pantalla1);

        pantalla2.setColumns(20);
        pantalla2.setRows(5);
        pantalla2.setText("0");
        jScrollPane2.setViewportView(pantalla2);

        jLabel1.setText("J1");

        jLabel2.setText("J2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(161, 161, 161)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String [] Posicion1 = new String[7];
    private String [] Posicion2 = new String[7];

private int posicionx = 0;
private int posiciony = 0;

private int turno = 0 ;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Posicion1[0]="X";
         Posicion1[1]=" 1. ";
         Posicion1[2]="2.  ";
         Posicion1[3]="3.  ";
         Posicion1[4]=" 4. ";
         Posicion1[5]=" 5. ";
         Posicion1[6]=" 6. ";
         
         Posicion2[0]="O";
         Posicion2[1]=" 1. ";
         Posicion2[2]=" 2. ";
         Posicion2[3]=" 3. ";
         Posicion2[4]="4.  ";
         Posicion2[5]="5.  ";
         Posicion2[6]="6.  ";
         
         Random ran = new Random();
         
         int espacios ;
         if (turno == 0) {
             JOptionPane.showMessageDialog(null,"turno del J1");
             
             espacios = ran.nextInt(3)+1;
             
             posicionx+=espacios;
             
             JOptionPane.showMessageDialog(null,"haz sacado un :"+ espacios + "te mueves a la posicion :"+posicionx);
             
             for(int i =0; i < Posicion1.length; i++){
                 if(i==posicionx){
                     Posicion1[i]="X";
                 }else{
                     Posicion1[i]=" | ";
                 }
                 
             }
             
             pantalla1.selectAll();
             pantalla1.replaceSelection(" | ");
             
             for(int j =0; j < Posicion1.length; j++){
             pantalla1.append(Posicion1[j]);
             
    }//GEN-LAST:event_jButton1ActionPerformed
turno = 1 ;

if(posiciony>=6)
    JOptionPane.showMessageDialog(null,"J1 ha ganado");
         
         }else{
                  if (turno == 1) {
             JOptionPane.showMessageDialog(null,"turno del J2");
             
             espacios = ran.nextInt(3)+1;
             
             posiciony+=espacios;
             
             JOptionPane.showMessageDialog(null,"haz sacado un :"+ espacios + "te mueves a la posicion :"+posiciony);
             
             for(int i =0; i < Posicion2.length; i++){
                 if(i==posiciony){
                     Posicion2[i]="O";
                 }else{
                     Posicion2[i]=" | ";
                 }
                 
             }
             
             pantalla2.selectAll();
             pantalla2.replaceSelection(" | ");
             
             for(int j =0; j < Posicion2.length; j++){
             pantalla2.append(Posicion2[j]);
             
    }                                        
turno = 0 ;

if(posiciony>=6)
    JOptionPane.showMessageDialog(null,"J2 ha ganado");
  
 
                  }
         }}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea pantalla1;
    private javax.swing.JTextArea pantalla2;
    // End of variables declaration//GEN-END:variables
}
